USE MASTER;
GO
CREATE DATABASE TESTE;
GO
USE TESTE;
GO
CREATE TABLE CLIENTES(
 CLI_ID INT PRIMARY KEY IDENTITY(1,1),
 CLI_DTA_CADASTRO SMALLDATETIME,
 CLI_DTA_NASCIMENTO SMALLDATETIME,
 CLI_EMAIL VARCHAR(100)
);
GO
CREATE TABLE MESAS(
 MESA_ID INT PRIMARY KEY IDENTITY(1,1),
 MESA_NUMERO INT,
 MESA_STATUS INT
);
GO
CREATE TABLE PRODUTO_GRUPOS(
 PROD_GRUPO_ID INT PRIMARY KEY IDENTITY(1,1),
 PROD_GRUPO_DESC VARCHAR(100) NOT NULL,
 PROD_GRUPO_ATIVO BIT NOT NULL
);
GO
CREATE TABLE PRODUTOS(
 PROD_ID INT PRIMARY KEY IDENTITY(1,1),
 PROD_NOME VARCHAR(100) NOT NULL,
 PROD_IMAGEM VARBINARY(MAX),
 PROD_DESC VARCHAR(100),
 PROD_PROD_GRUPO_ID INT FOREIGN KEY REFERENCES PRODUTO_GRUPOS(PROD_GRUPO_ID) NOT NULL,
 PROD_VALOR DECIMAL(30,2) NOT NULL
);
GO
CREATE TABLE USUARIOS(
 USR_ID INT PRIMARY KEY IDENTITY(1,1),
 USR_LOGIN VARCHAR(15) NOT NULL,
 USR_SENHA VARCHAR(15) NOT NULL
);
GO
CREATE TABLE VENDAS(
 VEN_ID INT PRIMARY KEY IDENTITY(1,1),
 VEN_CLI_ID INT FOREIGN KEY REFERENCES CLIENTES(CLI_ID) NOT NULL,
 VEN_DTA_CADASTRO SMALLDATETIME,
 VEN_DTA_FATURAMENTO SMALLDATETIME,
 VEN_STATUS INT NOT NULL,
 VEN_VALOR DECIMAL(30,2) NOT NULL,
 VEN_USR_ID INT FOREIGN KEY REFERENCES USUARIOS(USR_ID) NOT NULL
);
GO
CREATE TABLE VENDA_ITENS(
 VEN_ITEM_ID INT PRIMARY KEY IDENTITY(1,1),
 VEN_ITEM_VEN_ID INT FOREIGN KEY REFERENCES VENDAS(VEN_ID) NOT NULL,
 VEN_ITEM_PROD_ID INT FOREIGN KEY REFERENCES PRODUTOS(PROD_ID) NOT NULL,
 VEN_ITEM_QTDE INT NOT NULL,
 VEN_ITEM_VALOR_UNITARIO DECIMAL(30,2) NOT NULL,
 VEN_ITEM_DESCONTO DECIMAL(30,2) NOT NULL
);
